feat/10: add Suggestion API
DGU-bamboo/bamboo-back-v2 pull request #18
Opened 2023-08-27 17:35 UTC by dudtlstm

suggestion 관련 api 작업 완료

close #10

2023-08-27 17:44 UTC, 0seoYun approved these changes
실시간 확인이용! 왜 Postman에서만 되는지 나도 궁금,,

2023-08-27 17:44 UTC, 0seoYun commented on suggestion/views.py
> +    @action(methods=["POST"], detail=True, permission_classes=[IsAdminUser])
퍼미션 클래스 재지정 안해도 돌아갈지도.?.? 아니라면 유감입니다..

2023-08-27 17:44 UTC, dudtlstm commented on suggestion/views.py
> +    @action(methods=["POST"], detail=True, permission_classes=[IsAdminUser])
허거걱 당신 톡 보고 커밋했슘다 ~ 저한테 댓글이 늦게 떴네요

2023-08-28 04:03 UTC, tkdwns414 reviewed
우린 자격 인증 데이터가 필요없는데 자격 인증 데이터가 제공되지 않았다는거 보면 영신이 브라우저에 쿠키나 세션이 남아있는 것 같음. 시크릿에서 확인해보셈

2023-08-28 04:07 UTC, tkdwns414 requested changes

2023-08-28 04:07 UTC, tkdwns414 commented on suggestion/views.py
> +    mixins.CreateModelMixin,
크리에이트 말고 필요없지 않나요?

2023-08-28 06:28 UTC, kmjenny approved these changes

2023-08-28 15:51 UTC, dudtlstm commented on suggestion/views.py
> +    mixins.CreateModelMixin,
필요없는 게 맞나요? List랑 retrieve 쓰려면 필요한 건 줄 알았는데 아닌 건가요 ..?

2023-08-28 15:52 UTC, dudtlstm commented
그거 시크릿에서도 그랬음 ㅜㅜ 아침에 다시 확인해볼게요

2023-08-29 00:03 UTC, dudtlstm commented on suggestion/views.py
> +    mixins.CreateModelMixin,
허거걱 깨달음을 얻음 유녕서 덕분에

2023-08-29 04:43 UTC, tkdwns414 approved these changes
나중에 다시 보죠. 일단 작동하니 ㅇㅋ

2023-08-29 04:48 UTC, merged